BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "normacore-x8"
BBFILE_PATTERN_normacore-x8 = "^${LAYERDIR}/"
BBFILE_PRIORITY_normacore-x8 = "99"

LAYERDEPENDS_normacore-x8 = "core meta-arduino-nxp meta-tailscale"
LAYERSERIES_COMPAT_normacore-x8 = "scarthgap"
