export const CONTROL_SLIDER_CLASS_NAME = [
  'mt-4 h-4 w-full cursor-pointer appearance-none bg-transparent focus:outline-none',
  '[&::-webkit-slider-runnable-track]:h-1.5',
  '[&::-webkit-slider-runnable-track]:rounded-full',
  '[&::-webkit-slider-runnable-track]:border',
  '[&::-webkit-slider-runnable-track]:border-border-default',
  '[&::-webkit-slider-runnable-track]:bg-surface-primary',
  '[&::-webkit-slider-thumb]:mt-[-0.3125rem]',
  '[&::-webkit-slider-thumb]:h-4',
  '[&::-webkit-slider-thumb]:w-4',
  '[&::-webkit-slider-thumb]:appearance-none',
  '[&::-webkit-slider-thumb]:[-webkit-appearance:none]',
  '[&::-webkit-slider-thumb]:rounded-full',
  '[&::-webkit-slider-thumb]:border-2',
  '[&::-webkit-slider-thumb]:border-accent-data',
  '[&::-webkit-slider-thumb]:bg-accent-data',
  '[&::-moz-range-track]:h-1.5',
  '[&::-moz-range-track]:rounded-full',
  '[&::-moz-range-track]:border',
  '[&::-moz-range-track]:border-border-default',
  '[&::-moz-range-track]:bg-surface-primary',
  '[&::-moz-range-thumb]:h-4',
  '[&::-moz-range-thumb]:w-4',
  '[&::-moz-range-thumb]:rounded-full',
  '[&::-moz-range-thumb]:border-2',
  '[&::-moz-range-thumb]:border-accent-data',
  '[&::-moz-range-thumb]:bg-accent-data',
  '[&::-moz-range-progress]:h-1.5',
  '[&::-moz-range-progress]:rounded-full',
  '[&::-moz-range-progress]:bg-accent-data'
].join(' ');
