#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const stationAppRoot = path.resolve(__dirname, '..');
const workspaceRoot = path.resolve(stationAppRoot, '../../../..');
const workspaceCargoTomlPath = path.join(workspaceRoot, 'Cargo.toml');
const generatedDir = path.join(stationAppRoot, 'src', 'generated');
const generatedFile = path.join(generatedDir, 'version.ts');

function resolveWorkspaceVersion() {
  try {
    const cargoToml = readFileSync(workspaceCargoTomlPath, 'utf8');
    const lines = cargoToml.split(/\r?\n/);
    let inWorkspacePackage = false;

    for (const line of lines) {
      const trimmedLine = line.trim();

      if (!trimmedLine || trimmedLine.startsWith('#')) {
        continue;
      }

      if (trimmedLine.startsWith('[') && trimmedLine.endsWith(']')) {
        inWorkspacePackage = trimmedLine === '[workspace.package]';
        continue;
      }

      if (!inWorkspacePackage) {
        continue;
      }

      const versionMatch = trimmedLine.match(/^version\s*=\s*"([^"]+)"/);
      if (versionMatch) {
        return versionMatch[1];
      }
    }
  } catch {
    return 'unknown';
  }

  return 'unknown';
}

function resolveGitHash() {
  try {
    return execSync('git rev-parse --short=7 HEAD', {
      cwd: workspaceRoot,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
}

const stationBaseVersion = resolveWorkspaceVersion();
const stationVersion = `${stationBaseVersion} (${resolveGitHash()})`;

mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  generatedFile,
  `// This file is generated by scripts/generate-version.mjs. Do not edit manually.\n` +
    `export const STATION_BASE_VERSION = ${JSON.stringify(stationBaseVersion)};\n` +
    `export const STATION_VERSION = ${JSON.stringify(stationVersion)};\n`,
);

console.log(`Generated ${path.relative(stationAppRoot, generatedFile)}: ${stationVersion}`);
